# Run build & deploy every day at 04:00 UTC
# This ensure that data is fresh

name: Daily build & deploy
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jsmrcaga/action-netlify-deploy@v2.2.0
        with:
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: d7108b6f-bf25-4bb0-a32b-abe072c18daa
