name: Publish
on:
  workflow_run:
    workflows: ['Check']
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        package:
          [
            'publicodes',
            '@publicodes/react-ui',
            '@publicodes/rest-api',
            '@publicodes/codemod',
          ]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install
      - run: yarn turbo run build --filter ${{matrix.package}}
      - run: yarn workspace ${{matrix.package}} npm publish --access public
        env:
          NODE_ENV: production
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_SECRET }}
